name: update-deployment

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      url:
        required: true
        type: string
      ref:
        required: true
        type: string
      message:
        required: true
        type: string
      app:
        required: true
        type: string

jobs:
  update-deployment:
    environment:
      name: "${{ inputs.env }}-${{ inputs.app }}"
      url: ${{ inputs.url }}
    runs-on: ubuntu-latest
    steps:
      - id: app_version
        if: startsWith(github.ref, 'refs/tags')
        run: |
          release=${{ github.ref_name }}
          tag_body="${release#*/}"
          echo "value=$tag_body" >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        env:
          AUTH: ${{ secrets[format('DEPLOY_KEY_{0}_{1}', inputs.env, inputs.app)] }}
        with:
          token: ${{ secrets.CD_PAT }}
          repository: prepared911/live-clusters
          event-type: update-image
          client-payload: '{"environment": "${{ inputs.env }}", "appVersion": "${{ steps.app_version.outputs.value || github.sha }}", "auth": ${{ toJson(env.AUTH) }}, "app": "${{ inputs.app }}", "ref": "${{ inputs.ref }}", "tag": "${{ github.sha }}", "message": ${{ toJson(inputs.message) }}}'

      - name: Notify of Deployment
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: success
          notification_title: Deployed ${{ inputs.app }} - ${{ inputs.env }} — ${{ inputs.message }}
          footer: "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|View Head Commit>  | <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks|View CI Checks>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEPLOYMENT_SLACK_WEBHOOK }}
